version: '3.6'

volumes:
  censusblmbvol: {}
services:
  server:
    build: ./Server
    volumes:
      - censusblmbvol:/censusblmbs
    ports: 
      - "3000:3000"
  app:
    build: ./FrontEnd
    volumes: 
      - censusblmbvol:/censusblmb
    ports:
      - "4200:4200"
      - "80:80"
    depends_on:
      - server